### ISSUE TITLE
Contact page - design a google form and embed into the page

### ISSUE THREAD

**Issue by rohitgeddam** [DSCBITDurg/community-site-client#5]
design a contact page in google form.
fields -
name, email, contact number*, college, queries.

**Comment by carrycooldude** [comment]
I want to work on this @rohitgeddam

**Comment by carrycooldude** [comment]
DONE the embedding

**Comment by carrycooldude** [comment]
@fazer1929 pls see to this

**Comment by rohitgeddam** [comment]
good work
